// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./user_mock.go -package userclient -source $GOFILE

package userclient

import (
	"context"

	"go-zero-mall/service/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
)

type (
	UserInfoRequest  = user.UserInfoRequest
	UserInfoResponse = user.UserInfoResponse
	LoginRequest     = user.LoginRequest
	LoginResponse    = user.LoginResponse
	RegisterRequest  = user.RegisterRequest
	RegisterResponse = user.RegisterResponse

	User interface {
		Login(ctx context.Context, in *LoginRequest) (*LoginResponse, error)
		Register(ctx context.Context, in *RegisterRequest) (*RegisterResponse, error)
		UserInfo(ctx context.Context, in *UserInfoRequest) (*UserInfoResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in)
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest) (*RegisterResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in)
}

func (m *defaultUser) UserInfo(ctx context.Context, in *UserInfoRequest) (*UserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserInfo(ctx, in)
}
